language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    secure: bOCAFohtjerbNB4k2B8KrukBl/+EBakyTr2EQTo4xa+kwdqJI7KEwaTvBHTut2Yi4K2qjrEG46UF3QQMrjOqZd/D9qpwOOb4u3zPMu3A1qzH/6TITWMhNB4bnV7aTbQ9SQ959zX6NtQ+87piV+eZK++mJ3vaxJ07urlZV/u9z6ZEvqrbvlEVEZ+pVAt0iuKSkYru8D1m4novggokOq+3+VCHRJvelyYyBx7SqSSjiXJD9cfw4NWko10dxShYFDwv1hKvO37i25qZf1RpAUX8MCMeUkkNfij4e+jNoVMkwbUlsF01SeqZHRe4/OqQtSu829spHq+3TEDYUgC2Wcx76KtEf7YqRC/e7CoXDmNq+VyjvfL0MgVhxL4z1GkmBHK/DhIJcMqsN1fTbokhK2FhcOtOR0LzdtjCBluYyKI58xeaIth0RQ+WBN9O1CAwDnCZbthhfSmg+RqFS+DcgZZ5DYotoQFQ/7NEPNzrAyt92v8VJSi/BJu9Nzt/ocYK4IeRX+y0ujHvuGnR748vz7TgN76IGpjL1A/PxwQW6zwM0neq2nZwbYelfXF+9u2G3jijHctRN/dY88kwNuRDQFbWmTSATm6Av3pJqO5MS+IqcdyiT10Qb8wpLt1qj+LEfiE/k7f+q6JrtX9odvSGpDPxPYC+2nLfibvTH0B1bzWzfAs=
