language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    secure: Kcizg77W7yJOjxuWSN1izxh+BiJwskYFb7s/Q3x5kXOziced+NSkzT9mHgsKvOYwZ942WrogaTzE4To78kEeBjoLeZXIYwHojiCN8qyxe2ye3xkPZAdm81NXYwGrjv/lKsD/piYK73uhSKd+inhymM3sS3b+d/6FbBTs4Mz9bZ1NW7VtAn7F06AURqJ648yYioUfcu9yUbufTssIfSXjz/DpscFjz/XRbMqKrj249T1RyJYJ9TupCW+zhjBIp+mkJe8hyapRu6EnlCiFiuI932FN6IzhY4vGV7iXr4Kj+IcbAsqKsWuXlFXuu1/hJAAEBzoa6aqKkVCqZw63da4BYqAOpxb6ZnnKHIfSOpfuftS1pU3FVw2CT07uhSN3a916NGwnj1bCNUoDYmYXSI+CWexsf5SdsOk63xn7x8dYA+Udvulb5WTN2JWg+75aiMsEQEWS3J8pTRFGGh+EX/EBe5yPjft8+wKlA7PUkC6Tetm07XeyxcHa7jraaWi/cuPqEsIjdLUwzkCs8mgXWafgzazQqTRkV86TZM14IJggg4Qy5Lc5JtLvMpzRYFLTJcUg6CYJZ6SnuUb3/ZSz26W9KNAe0KY72/8viJo+yAGQ6n7/LWDNB+BbavhwWCFBQC7NK/d4DGq9AVc0T1gltpyz4zZMlCqUyZJsrk6P4n32sZA=
