language: node_js
cache:
directories:
- node_modules
notifications:
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    secure: AjMVWMAvWwNAmatiywDpEdZCNWMFItbMlJ0XhPfrmcR33+f5D5NVPRzWPBtnT9Y7hVc1hUOxk8lAsysAtRswlGuBOB/uSm4LkuwveLCyqdecCoiysyI59gM9+zL+kdVT1q9Hy2/0Fg46D9p5XJTy+SxeboCjyI8NcR+CvsS+5b3N44gwMzEqxV+Imk883M+1CEOCRsCSJw52HDHUD8MYvW7RvDa6nMIAJ7wZR6ar3gmG9eB5QjCwKAoCrWz6evSjUwdMk3R3F8CyAtNdrN4ZCcIADMKxBrRB2gryUsGsZ79evfX7TR25FqbTXttESAnO8PWHl2cngz14K3egEwWzRRfW7TviNwt3pF/Xjh+G/FGZwOS7YRmJeiZzH1NcHxScl0P/g7qSyxRXzbfT606sA3FapbCIBNHm3D3OZNfzUFc4MNWQrqP547P3VlcLDKWPBJR3Q6bhCgvwlwLunzI/wWJjh9LmxJDA6yO+5UuA0P+oHTgdedPU5b5mShP0kfNpNoXgOTaoe46seiJ02Kgu7/XWtUO7Raik5JYrpLKv1aC7wRSqj4nsrxnWeW0a9wV4IFIdTyxE9n84bxbe+Ol8S2x0xBQCniGLBaexlJVPKCUYuOtlM5e1zojlTS7su7vvRGlLVXNzuMG8qoRRjcFq6IOPTKr8M90Ybt8oKWfHQkI=
