language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    secure: XvFKblct3MIz+srX8/R4Kd7PnhrxOSxM2YRmSLhdvVjsBPUE1KgL6IhdRkrsnbWoxFVe/75Yz54XpDiqKb9pISFKvDbjek7i+EKKhk0qpHl8BWdixCIHov+v0bTDeMyzIuXb1RNuZWW1ql0ABaLjUs3220/nDUvGI1ZJk/Y5DV/jQOGHpQ6Up3Pky11iEA25O/MDJidRGOIgrCvhPYlxRDHVbosnxL83us3Qd2KBahrPBAMVbUSF+T6y4G+h7hmOkYhi4eiCCOSa9Nv0Ov9ZKJO2L4I2G3iUBMtmJOZnArlXGtPjOtuJCBR2FmSau5ElbjGr8KvOu4hBU419TeSN8Ryzc4is6K988cY/Oqd/W07WE+ELA7JBlIY4S6zR5FwBUz6fXh6Gpn1n4ZuDIf2feGwGQ3fGa5UMfpdm22U1CfcklZRL16Dk9Lauv3uWJaqBAngPMe2j8VzKDPJzjYQUNMdtgI3sRzZyxR0++Cjneqo8YHxf33fV2vOlttFXAhlVJF9YfB87nqzSWgNFKC/vVIgTuOaLwKAobIz5WzIo5g+Ls0FHYd4UYxhuRXYnJKBlALmksP+z4QKKW8US3tC7LQOFpXxTtP6EK4byr7edKAmFFHZiAqBhIO2yDVAFM+EudTkqLyNtygP4FL3bSNkIkbgF/bzNWuo8NR0tBKXXP30=
