language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    secure: b8IEE7ombCK2uSdP97rkYDsLbZbHKPipREeaXb55JZ9ceAyx9RE7pTD4ScWLNIxctQ/mFjhgi70lmyv6LSYXrTU5uBvzUtOE3b0Z7yQwRQgc6GA1E6m4kQcE1dMOLlyww7jMRlZvja/qX7NUDwVSjkmqAdp84097l6bXliEFyRdbRtmrH8j+XP2UmCjPfgphyqR8/bhOuGW7OzZAAoKD7C/7upuIvj3qgg8RW0HzFMxWxdoA4FCzM7dsMFh9gCEkNfA7JLeTkRiIEr+rYDq5gim5I8hBLAt5v176FUxX3P22jF8IxbypTQ2gFUXRXWPhF5T0i9+GXdpIJV7WoETqQHkZ2QoQQroCh6bcaY/pEa62/osxnC1uyjEte1IT4q2FVw7KigsG+FYP5zzoOyAqwBOMrlOW8XMQDTux/yx3YctsjsfQyaFpBZdX9kYeWn0+Lrtk15ZGJ1FvCINOBPf5GJE/v6FZlUGKOnfHN5I3WP/VnjlCxF0i1LhhJqPmlwiToIvncc8fJ1om3WpvbhUoz1OTj59qum/tFBeBQPInGglULggH22qjG9b3py1EkuJx5KumWHKOURw4qOhMgvTx+byTRMoQ2qB6rO+YyDK5LW6PP6OOY/OL4nqPWF3XdqMqwoQ+inj9oRjWsuL+sgFmUzy9SynDRy8y+KQ1xJ6gN4U=
