language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    secure: M2W4acL9z84J8bR2ibx2mfxV9aHRzgeZd/1iDi28R477wImb2d9BZkKlo1nSwusMBDC4zPw0C3JezlwLv7zic4RamJeeornGKzYrF8aZDi8voezSFbBO6HmBNKWZoTAJZl1bjlOMQG60binu9YJ3VKnu6uUQ2CL3rirx9HU9okrnKDOr/k/tgwyyCovuyU/5K/OGijRWRVEehTjOJfTpaA8Q5++JfRwphsizPOtXUDQtm7/Xb5Me7T+g4NlTRIsIJ6dSlFEesZr5QI3zBhBC7FQPweuYHQrhzUr7xm/Rzi0zsCIfMvbxZyPGYepR5W9Kwfdg9jhZr2BpZEtpWqkH6ntg38HYeSurn57cTob4WUhFftP6ZIlcohCO8xPVLKjzBz0mydwlm8eBp+jwaSprNZ/4e+/LiFwjLhnEyPG5Tvk0mAX7j9+LWR6QUE7SKyexnIQqGEwfysYHL5y9gioao9QK6R8UTtvEwGyIE1msW9ky77GAZwjFi4UpfeaBAMBVKHbzjhaCOwaSNPbimlIeRRfYEYZHt7bLq0kUcAUhXmfEySdjRyFHGVKNAiqJRqAkIHR5wUiivUwvlNXb55nG6z/AhIr9yyTjAKPKQPQr7pTpx1J22PSbbNZ8SXAf+lAS1/q276BOZDI1edud2gzTKYzWq4qkBpLewXG+GRMhA+M=
