language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    secure: e7gH/6XsbvLPV9QsP9TnYhfbiwLGVNmNeRak/KHj+UIklcITWOoK3dCbcrPWNhtVcwCGzF61Ni7+EVC3sWZITpiDbNolchY8q13mLsnd7usfuQksukgptZb2tltJv88a8VIQti1SJRqzNG5FgxxU9daKb/t5hEMFnjxQTwzVIqnLysGNTNLEgWtAdUfaOY3TCWf+1Rx6yC02QbYG/QxK2U1FFNZtScXIYsmkyFuZdJ3OIk8dnGxz2eo9f7zS5O19pfbqhdSH9jfSy2qfywiDRxhnfH/n9bC5I4X+Dpv6t2HnDUZ7FOB3kZMWnEp8vTHCsjDYeBTLLJShkyY5XZufqaEzxPaZM1uVskbdh2tAF3nVPAp32zT1jFJ9K73ATeUZO6Lr/e9g0x+0+cmCi1jnACxSBR5MJsHfa4e2k7gOKn6wnRX7yA4tqqXm31+eDCDQVyDblmZxnBZ+j0sAnwhdCjBhU/tARJVKY08PUyMxXRVzmtVzuwkVDYXwvFgJ2RKwvrmJ+TLP2NebsG/yMYPDXvQYBuv9/4hQmOO5sZxij1KUgjtb3fD4vzNgwWf6RNz9S1ZARR5NjlZ+iKcTk6ChITo8ncK6KqQ0tV63Qj7aOjitRVudgqL+toz3WYrl4hiA3yvEeXfAdnm4Yh5DVwSFb7AGAa/Pbc+wmIM5AKONkYg=
