language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    secure: bD9DRWUgCbO4/iLSd1F8uZrAIplHMunzPsJFyEaPMat3KEUVeIKz6djQzM1OzOO7RNCPxmGvPG8FyTgsDmW1ZEQv3jpxvKChDGm5C+IckgHBUu+L1cUZeSFiG/sokiwCC4xQDdkeKHSbhlAlis56iXCLIZdp7LzYgKzHVGJuRo/CIOhJBdKe8t83MknUgvc3kl1RDr+WArQkk/wcAcZzDbPBQAqCDB2nnMGeGdXThbBhQPoOUD+1chL0JbQRQYM0SaZOtRPkutrWivNxgWOGD49FAmKePL+gTOWbZbv3wqsiikwrzg165CTD52wOBf4/N6ugwr9IKI9+3QhqB8CIQR9lwObSr1h0n40cZO0dS+SKTN8b6CQuJwf0FTwNvTGRgtVN9njKnieydbh0gF/Kneo4MH971CC2pro5Uy4keEVU8umlgLA/7goQK7jPto59idYElIRgSrOQlbeCjiUrG3J3ai8J2vHFHIJVWmQQhUbYtNb2Qp3UK5tiz+58TMH69ikITUoTfAz3crsQMN5i2RfTZKMecbIRlJNp6AuBlg/B26yoTmFfmt1ExqWanqoL/FAwLWXlaGzZoXqPTbIEj0YfZB8LWXACurAVNc93SHdLENJkbv1zJxcDkh4Q5j99RQMaWBLe580Pj/xwCk91q9Y3HlFR+bXFmI9fPo4cbrY=
