language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - secure: XfZ4n/4ZUmindZqr/ofRzVRdxMJblOJwSEntZzojPl3jBSsLhWoPZuUL5DXPGS5sJapxCRu5Wfp56Zv6WUxJCth1axRA3OAAkXbUtuSlLffqpWc5VIZPeOFeko15Vk5Spwz99wFtN+ekJ9wH5U2/d3X8q9RaUms3hsuqjvzAwHljIdHsWejnmWIxQ9vWrCNl6qcm2KQbGkx0N6xBxQqVSh1OH+8YwVoLhCpuw/INUHZE2dx6wOx9DU0nYmG+SWP43IWKC7h2n3j8nboDOYO3VqSPOV1hARdS+mzL/TJ9ZvPgopiBa6A0gXjm5wQFaGlntBTWhs5UStsyBKN6X8/cZ4twJhySuzXpbvqYIw3W68ltsD7TaDdN4Ir7ffFZCukudJvF43ZVWQPokfn1xwZxXis/O+Rs1QCgYZxzHTMdvLcT9+QRqyij0ZtO53AmUvkcUEeByyJ8FXecI+sDtJBa0UzIkCql0KWA3i6rTYvTiD2tDxXCWL5dKLbl7v4+MmkuncP9Zsdh35KgOr5MwIM+5ph0syMwPb3huSC8FqE7eMQ2gzAu3P4J3nyyFyjxE8aEekL+VVI69XgNhJYv7Jz5e0lAiiKywNJ2K2oJUb3vhHwUpR1h5srSo8gxjU48JToyLRZqex8a+YYCHloFWYyMQv22EXla0C4Dq0NAbYF9hIk=
  - secure: TDVhXeKTkoQbHYh1M+JE1HCvqWh/9ymg9q66N7RE7dmm4tDST5ooAaZz70Ap12m9EM9FxeqLahf419gDl+3EZXH8wm1tWcylKmFOZ+C3Y3K/xBKSdq1hJWucj3Kkrp4IbiF6iogPwmaM4brXo8eZwzhmn2a15OJ+wghyd54Ek4PSS1BeHf2jgnAMoEmCePO6wECfF6E76CQ6WfSyZYbzmV5tQsV5gp8xAgydJ0T7ko9Mb+bJwJVOhKj2Cl8PNruGaEyT9UbEN8OPpoc83H5yF8/aRWG251M8+rrY28lyYZTFAD4O3b9SRvE4xRChULa54AS4tOWZzzrKDADKfb8pEKijlQnVLLtF8Bwww8ogl+RznIR6tom4FQy5HL9J0Y/Ad6D5XryC27FiXMPw/HQvCe5rsFrz99V9qnaPvPxm3nYvwbWEhXYyA23+rqVRbMIq4mxtOwRrJsaiKpBckv86b8WEQoluPZd4JZbgiHshcn8UXno56EDB1pm8smLnnfrM7oiEgr3jCudn3Gb/nY7Jt3pmHuRfc4cAQZ2IjwmJcKUj2ebjRhPevFnUec5tTTjZVPeaZqzm6ux23Ir4jS86f4GdhegZFQbbFpLCwOyWnu31djKKutxME1YJUoqKcrqjbhjSA5RZyNG2MtZCJsvL6QMQ8w8IgK3LMPH8q/drz3k=
