language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    secure: a74wWrqIfKEaJszyKPGwNR9t/VUWnH1o4zhOZD30G2JetdSAUGKGHMnhPpVbNvVIGvBFCnolZUImZrA2H6G1v7ZSJvq859Y1JyOTIbAVAm18vwfs9DLObZxX40JLyG7fYhgd61MR60DQj3KTcjR5jHgOVBZS5E4bi7zOoBFvm0BSaJfEnDFYHqJhlkNaSeU9bKNK97R+7Q1JG4ZfU5jXhoXBmEl38ULYQzwnlMoYVGxAEj4IeI23SLSw9Zbk/dmaxp+c3+feXWgnsaRY27sYlKumluD1PEXBZJEj3ufEWS/SBEmZa9EsYm7iXQLKhLwYD/mHNwDFojl6SCuVjxqyApOl9z5lBJFexRkw3QSh5kzLBtbYtnL45bZWFeCelaIqm+Ba5qe8zQCFXZZXigI9Qir/pdnyKVY/HA9jBkzvRIuep8gEbZsaQlrPscp1eW+9ABn5VSe+RRRe53LhAQVzrvca7Xc9Vbr7x0fdKKVDNDcosBP3ioXg6NKMk5pSBimiMm19JIKsiZSaeprdbGtKpY2u/sUBAkQCNqkdx4NjWL7nvVsY96V0KWF4W5WM/8ExbHfD8kUFIFpv3nZbSFzGdYMyLcjsPffLtWO25KRhdSRjlQsqkC0z7OcTHo/2Rr+4ZWUkoDfBH/CRluWoy0doZXROwoee2G7BUBpdzURSmSg=
