language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    secure: KCW6FJxbJB+iwc8lSB46YPaoqahpBTnREKwykROTZt6pzGAdA805a6IQJ3nFh6vm5mPqBUPV9kH+k2NAfhrK2LhSAra9oqxeTzWPrsyzKGYhHPZfjDr012i65dpcISrpFXqk/UM+t15UhLqpRJ4blcR2M+72MCJaeuVIN46TTm4Yvl4qm+XRHZp2EpFzWSIFNhpZ8BU3aJ6+4NJ8RG+pz8/5XWRjZjcEOP+2dLxa48r7M8FDjTLRVYLV525+Iq898qtStj3ikZMg6OsealtOstbwpi3gfGzhxH+eK0Lc7UPw0iOpSNn+CEzudlnix/A3svCGnS3ZOPHJrzi9YzAW7iV+Zc+sOElOq4Po0p8D5xZPvpRkeNQEhHkFpbGNtz2/I24Q7SQ/fRTDlnmzmaNz1vfQgTL3AYP40MQajfJkhsqXjx59UyJb50HdpLef4hC+b6MHGUFuo+FQ4qmLLh4V5H/6RKzpr4OSPXA/2knw6y8orUyT5xJFSxc+2TgHDJIWYr7LBCSaELTOC4nGzPyoPnsbpr1TaFCZ/vVz6goHaee/yudSZ03Wr0nxAu/g6fJBNVJhXQUKaiVOn1+M5aV6edXCXCw9RtD945Q7V32q8RiCHnt9iXx9qgJ1g1jZoMmJCG59lrcqJijyS8dkC/j3jIPrQYR5Fnh6w913GT5PboM=
