language: node_js
cache:
directories:
- node_modules
notifications:
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    secure: IGFjq/qaZaygnzf1lYmv/w/G4A/EVeX/pvnC5e6A3Po/vFqwZMC+4fNVGoTxg46XnmweI0pSmpN/9Vlg/4wBpry3cXHwcPMzXNknK10BFagurpN9DKIWR2liaGpEAPRyTo2EgGohaPxoKIzOuya9RdmNkGPCNyrR7hgnqKT5BdarBcS7FbdlW8vX5RODiYLmMHjIN3kB00/k9rlLNrjyy+3NjZ4ALI0fqk6MT+3+2jnMI+ykTgfYhmwLJR2vzmo2tZwIWLcMy4F90Yr02PHoVfq4v05vtwaydskgIuw8+Tlazrapuw149W6o4hqWSGNNu1+bVSy2rupQGE13puSXV70N3G2IOIoc3POREZuSJN0kPUV48ElRaIDOUxwRXJkGHhszHPPNzsZ/qEOib5buXhqNnVxygS+MiS2gKJ9i3awSFoprsnKdtsF9zKipwZuHeq6juU6N69OWQ1Ou2n1jLbVX2QJ4rDIvAeGHHwRNSNkTdA0DfMECx8lsphwbGkw6zbP0ept4HxTTMXE0jD0PR0LyNzUW3zLBWcK6U2hyEcwNFl4jBfcGXYjPlLS+e8Ir2G5lmqk+FX5RcYumZrZ/mGtXQE8H3lqmLhNtfTQs36vweobdjxfSxwxZYJbQDSrTmmi3Nb5uNYwTH9Iy0UNyMpRI/NZtPWo/BZKyFnR3z3Y=
