language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    secure: pCNrFVVl28YQ7K+dSDaqMBVfLeGJFu7DmXP0J0OcgrSo0VBgu99Qe4+pJKrSaveRXsuwmt8IVyP+Y6+Uhn6TQapaxwUvyqfC23YYZuwdsbsCuSVZOliZwsiRnE+8yq9g2F0BeLghXa3srHmfuIicphEUoBYQLo+Ag1A7y3SytMjw9Dl0Sr8u9VxpmjMvCz10KLZZBv14WjblXANxnhBaZ8pj3INgw1QxbECMPI/4O+QMxngW6poRXtQbv9brnr6A484v5IpMUVfl3Yv+c5OpdINL+kifj++NjyEZpVhBirNUYj5f6stf4QFG8TTfm/H2s1riLWRqWt7m/W6tyvoVADcnWparmZv42Y/6vl1jgmt5XfgmDNECfCb4tqJDuh3KNvVfbOvzUF35i5PcL/FksCoQuoKV4thTKLpjCSTlSAmRVZiJAgI1iXnE0Few04LlE7Ww3Q05XMB0RHYfRMLIYQuGVbHW1LEfbaX9qcGCLxe3buvEPL5UFutWzXL2rsrhV2zfm2qV6tnkGESipHQRTY4xXIjXzewTywQ7F9axi9qXm5Tn5A4i9MHQceEVlofVokNIq+g0FJB4WEKufYv/p5QCKqvYtPX4wT4MwYnZVB9+VxB7iXZa8fZqmI68RqNfsU2xxf7h9A7F6ONdAL+gNzjV4isKwZv07pnn0BzWuQc=
