language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    secure: NX7G3gKukTik2Xkiz5lvHrQzzPxv+nSwoYTjy6Ir7Tu0ETJbCtQWkLkDslzKSnzY4K6zVaS4aHLLnGC7RVmStX2Pp9949z3bGRjQgv7iYf7Zs1IZKEI6vhQaJPOeqxkEtgQ1n8d3nB2l1ONkbbUJ2sRJ85v23h0/F1RFj2DfjR4dxCFKZxE8o3JWUfxtxg6vF5H19fbuluRpL+4o08LoPhGr0Nh6kXiq78iLzvg1khjpL11wZyBa6mVWZ2WoX6U7WA48IiwhqZLfLGeZU3pwl2qOQo1miH4OB+WYfkshsuMctpT7wqQxOBu6/Ezq7W3HzxfKIteZtqAH+g46bVu3nrbBM7s2g8ptfjmy02lWEUICV28wdExK4QKi8u83AWAievT20fltfIWG+H3O0oM94cKX+s8fVy9bviTOLaCGJoXHJXJcoz2RhCmvWxwKkks3YcRHiWcwePRFojmU2n16Q5DA18f5WIfgCFmAz2eVRNpubEn36cykv1+vs7KvRKuaC7hLAKzWgye9D+hxT7q5A4qC0VwUwYomQ3xAcXtDmUdKQGAEzkTzPmv51E0NbfIocDnoO5etiQSLOQ8ABwWNK3cPdrJm2g07lL54JwjQYL9L0nukS+PlCGwjxj0Hh05eMpiGLV3Ld6jnZjtsCL23M6saQwua1YEVJj5cP7quTks=
