language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    secure: N1fJ9ZDELSc0gAjSw9BZYeALs7hSYBITvnWIbonZkxqHmPX/8z2Q3I4XuyGAovrKo1hLhUDuDlc3FewyrAeRe9XST6yAzPVaVOEwEC54YKClpGH9tPQt6/4zYXcz3Tg0N+k+tIghfQ47IbuE537EiF31LOe39ymQcrECo933f+whdMUcOjLWLGzP9oUXcx0UbjpzVX977g6tLWhtCfb9bsEU0ZQJJQfuIq9ii72C5O9FIRWVDuFZx/+Jd+4tQOb1Weg/scJnw9ORZnleSpZgDRG0Z42aoM8N+AwPhBTkzg/ZJbQ4ubzmv2Psu4DwmNS01y8Opt9n3V2VxMqFm/i4Vr21sCEtgF5Zx8wtcVWF2opHAVEK/IcZ4hQ6eeFVO6B0tTcKHNwQpQZR32pUkWK94KYfMwMJ1Yt4Xh1lY20QFPOlisJ2bSQ+1EevXLThsASrRx51PkNTe/q3G1m1xE51IzHdDSJrMw2SERO4lgldVlTc0neOrQrTo7vEGHNsH+qi8SD8a4hl5FSIxvMsjpr+/QJfc6L0OMuyHwR/D96rml6CevTH5MQTV0EPRHQhX9BDf56jeMAHIxbstiQsp8T8wzZD/xKrwODVR5QmPuTk1c3WuXDWicHLTBt+ExeE5kwBS6LHLb6H3WOAMmJSpZYU/pOKG409Oymkq0ckC9/BPm0=
