language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - secure: SzioGGLImWn8oU5CfaEZZQ66gUyegle7D7h2ubSTOObBmqOI23pImkDSvf1YPW8UtMed2SVt0qfJZhyrWiPfhduyxOzJx/uelBrcUb+yFkhO43ggqbytUcYinxs1NuorsyD6hzH9n6E6b8Jv3Fqh6Db9nJ28+CCvZZBpYFcJnBnYtJTydLSV58x6apzwOug5Ol1kF1SRZo5fjao0tAg5ljbdq2Xnb9PIQR5GaWPad/SW+ornZiJYkojeTcDrlzKSRvd0SqtubXiQXjShaMcCtkqRQBGUnpOdbqiwve6lkPysHEJxc/oaBMFqYNyItGrOO5EcfQWhrFZ2PT4JC2Ssxk7pn8l0NpmfOW2YFMCgq3Ea09lpgYL/hXVv7rzGFQvqJpFB/+ZqWv8WvL31qrLyevEpLrYPS340+Zjq23RRS9ZyHcmexerOccJlWe3qnKO05k2eiy6E/ITyne6r7DybrRmfzoHkfQ7Lop2B5nqnQiPk49Kblj0o3kBECA4t6C6o+7RiksxJf6rLUftRza5kAqyGHy6egvhjyLZkhv43U48GnV87CvmGbpqy7MjaFukDyTkBBPvnN5VfpokoJjfuMTmoSJqJvJyXWPHKk0ezNDaSN9HluGlS1GCRzz0HO8YJDNkWJoGH+8HFM1Pj555etOhaj7o6RNj4j2/WaYgE4mk=
  - secure: YA3ul3hfmrrQ0oCO7g9E3XCE9gKU7NnJYbZoSNAnultFZRV8ydUjW4HEZsiazZbVWzz2kb4KQcRGz9FtqbuJM1VWkt+HahMvL8UxN96Xy2j+zOBRppEwuI4ko+tZWb1YPj+uT0zfDXXSc4t9HxNEdMNrbLi+KTvFphWp9ipcaAFzrcdIv2Z1tEg5yE751MgXF8egfJ/b5EX7JxC32SFIf6pFwgSLgikEa8IVPvn4Yfvp4aRVKeCc1IDZe8Z4TrBj2K1XY8ldJt3gQcq8XriITL6cw1yzQ3hBVDyHA2lGWqFHX3229nIRe4ItrWjzuCSWscz7yKU8isLmu8Ddp2MZG23ktA8ypHT7FPCLUk/3o9XiTYtArGiT7Yvqsk9N/fxseFEta7fqMkZ+FKDlPWmrCOK/ULwwBHFOoIgHukV7o+Ju4NHkNBwJ673MDCZChKQ+x/OodVlpmJ/TJEfOmLUgLIdV9NXXX58mYyAUykhmWkzy/aMgCXBccLB1YITPbXSoGKmss9+vQCPxTRyD4tY3FJTmkeNM9be51Qgj/vXflpmwhPNOYmiSqQ11kLLZ8dXK5oja0r/4llLXvlMVDYWbUc989cBRbRCSHsKptW5kzsuhS/xhgg7xCJFzXiL5WOHSwxx83vUKuEOCumbuBIJ0rTFGANN+vkG0tJaaztjDAhM=
