language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    secure: ZnAWomp+lxZPrxqCdD3Mwe8jBweQbgD8M48QhGoOqVcsGou+pk6Z8gCqf4ACvkFOO7bqywYhLsgcv2Wo53iiAp0I8CD6eOrNQo+ARvr7GSnRk44MGcQtwTETmL8WJasih7RAx9t+DENETY5u3I/U3bjKSF/RkZSAoI1Qgz9nWqeO2Vfk6y97+abBcisfFcAw7aV/o48qzMJOsS17r89xTRXIB83bCcGEF5dzTRawLB8Cr3zqb63umtVtX4VwDqVjfGGO9J/ZzZC3IZMLpTvrNo3JbRl0wLZqLNlHe4h7FBYKac34T3jFl/VOQEm2aQpPtpjZmT8ls+K3vgWXHo8KeJJS+PvIIWHGsCiNcF+CGEJIO3L1Ft1WO6oClXruY1F98AU4UreDg710LFO1zhDzWKWc6CwPnshf5yevY6h3aEn1TTpGokRo//74UEByViDJSVXw0Ge0emsUgO+W1KOGHxZMWRdQjz7ZYEMu694eZz01Bae0L/N8Aim4nKXLfbmd10+qeEp9VMZBCdKOqGekzBjDB+rK7jwZGgcGIq+AqLsMJxR4oqDRzdAa8gODh/ucnpidYdugp8YHpfDyl2UYwH2qvyuOmUMNxGpcmT5mS+vXIf1fDQwscG2Es7T2wIAh7RSrYFyRJ/2GuZLZ/Ej2zfAHp051a5qDRCcdQEZxYIc=
