language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    secure: IY/XAmgYW8da2cyEKzJPK+/pJT6hg+WMKNvl6sdwVQw2EjqyecTd0aolB9d81VH5b4i0tIhQEopbqRL7g/X8T3ezLyel9iZB3w+tSojQ115qVrhuvI6QJiPcpgHBBPaym2hichT/5IFIZPFgFHb/8REUQwDYPww8yi7NXuCHXaXWXu9EDKiytJt7hMHpJNnT6E56LGwI2uwJE0rGkmBJQQ+TIdCVbj7zxuh8PwjyYgI2/dd+GVmERv2hE9fZ4qzfwfMf+IxREIZxffImP628QYP3D2P9t6Pf8VW3gWn6AokYUHBpmL2/HMxLCcLjYgy+u2CvoO0sJ/Y17j1wCn8ClBtf2jqhYAb/CFHO1F6RHAAUwz/Aq7yHcfy8MowAQ/JAJF4g9JQHHIHxKSdD9D4XQOiHG9x1Kw7MwmgtSaCIKYEPELNABOBu3u2FPbCa4T/dh61iAXDDLJdCj1PlWRBL7VV717QIixrAKBlNnG9/URA14BPz/vfpyGMmB9sB9HA4hPuMDeP+Z2mfARS/oq7twoE25FFlkNhKGOywOVYTUOIjXOkKbuAiZruu+b57mFMeMm4UnahYiBBKj+kfAyHzXqvtd4i2NUgtJZzNML8lRpVOfMFSIunNx2X1oAgG4zcUc5hUfyBwaFD2yyk/9AAeI4NaQ/ikSgW+4kVawFrlgH4=
