language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    secure: PSZel8wyjf7a8+TPUF+iqWJxw1/c+GQ5rrRH3BYEZClmVvAmszgK0Hgu+NPFsEoe59kHbc802zQbvW/sktHwvSXfsD/GFQ/TQZ0ofiTJrjZTklozuaG58Fk+JhSQY+pareSCWLVpvm437mCMlE2Iu0XJUQ/gUiEWG4VFdAqdeaDAfXyMcQmQ6JyeUWzoUj2HStapIKRfsR+O1KK1rLxkMeMZp8W9PuBpOBZ8/0V+ldeskWqcUCtWNycDPoKii3t6RyAw+A0iNIWBZTAcmIBkdDwdZxWfRRZt4KZCHzOK3ZaXrZLkiIdYVp4nq6WwhHbRpwsPdTPwxeGJMA9mbCI4/wSQkY4xkKtE40XUZ0/jrJyqwyqqYTZNQRgIZiHqrr2nZ65GLl2X0Qyf5L5hAdssUoEW1PEzVEADK/1WZvixDxLdGPSEHfj5Q4I45v4NjiLgnf+guXybkH5Adz6cJ74ykW6/mbhXI3NndT5TQz6p7EiL93BUux4boQUoPZjlGgHZHzbl86sZD61rL7AY6LLJk4b0lFNsTvHkvzoSZwsZn96j5wCbKBOmk5j7Ba9p3v6xOJIKFnnaLI+P0j5YQeRnIlLNH0xcD0OcV8ENTIWkAEfdF2ybh5PJgZrVW+9K745GonF+4bTMN3GzbeZv+1HfnhvQqi2WydnY8s+gh9IGzcs=
