language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    secure: KDmFNcZN1xXt0EwFSA2IVAbaX3GbhlKZ0f8As2QXGW1pavKPcRyJw1IEuRwlFfY4lLdh20ho889uMc4HX2tzLja157Iy8DTMfLsbDvhmus0Y/pdy9y8zG7a1KwDomeVXRI3si2opWgbABHctJuhUlC1gJS4wdYB0sY77dHAeZ6IPAjjZtE/HyxGxvVn9SRBFZSNegk4I0SokUmTPQKwRa/nEj2YvoShBOEKTuhHRxxLjml3YHusxQLn/lLefcwPva+uoV2UW2aUQUoxbv+eApmDEKraCvIh/gg0mNRWmsyEqdQ3DLcRs293GWaNzQBmDpCCt8He/GL+/oJOnFc9813EQUA/dVwxpBJR0Q7g43OQeNF8ruO/iV6wlJr3HTOJL8LBsxYnmrV0H9hfp79LlDTcn84NnjOfUbb1tEc4+o2ewYD5aoF17MvtcO71sZnDXkqh2Q7E+rGBlAKTm8R1eo81D/dhXl7dShL5g+syKvu7f4CJHRpga6GJ/UkZvIvTvFmT82b9OsidvuAUjzWXZY7i+LOgOdey7HEddBYcLNzDf85ab2L/i4w0Wa+gaFvhwf/tDyYrFbVmihXAHUbO7X85pnm5pznhVVezkQ8p8A1PWINrRXpHsUxt23oLLUUpc2d0uUt0FNxngP0WmaCLZQ9z4jrhnzADnypinwVgDBG0=
