language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    secure: X+hZY037dcteMXDeOYw2mw/pWSRprRamh51zakpIVx4tvzo86RbgV9tEMfuesqSDah5TZGACt9DDOzD3dGxgeM4eWwYxt+kd6LlT2YhEucoMfv/6JwSc4ifRW+LofD6DtWyv0XdtaXDc/U4ionn93jv6l9S1bLjYMZri08wzGWFyuaiH8nDr6EsNCf3f/PF0Ak5/n9AWVRD31Vee1QbHXv14N1k9Vc2scTf0KTPKvbtQYidw4T+Y00/hkS9rb0t165iih9Gzc8n09sgg8hMFWLb98WWp6S/R/79t/34WgOqqYUVn14yB1XF68oIv6zTs5FyI6AR5gC79NdNjBIkSd4Kpl83xCi1dwf8AzXqstlvaPNzevVOdcB4uwnm+LZei75ZoKSyozcs9mOkFqwGOVoynyXDFX1mXvnbFm00x8+DkNSih/Vy2LD3M8ukYhsYLKBrh2kmisYKi/1U3/Oe/O8jaWbmBPxtFeoK9Uwvs98tFcQck0z5AZUMtPmJdG1/84Co2xeusINJldmx6EMpx8LPT074X5mVwuNWfo2B9O+sMUYUrJFAeF7vXUa7RG5iyPfWSJK5DVmAW0OiLbt1pfPKUUU4KnBLhHRFKm+PItPSts/AdJ9VeA/o7WcvZE08rFXITTgxTxv5/dntHsWH0KCtTEvRUBC532xSvN5R4M3o=
