language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    secure: Bsya1rnVwnwbyFir08s8mkmz+vn9EyGeZwZfuxCtMDXJkmcth2JK8x3O73YqzpX7i3GG+GinyjNhUY/viJAG/pv2UVJy5SLWfpPxCTjPH4g7VE7HG5oW/guE3wcJPSDd0/PTawpQUC8j2aVxYVcYIoFKuBiYf4Nbi7hGobbBa1SJnhPMDTTP4tkWqHia0q+gbFzbkMoKnU1+xXHSGmrGFNDUgi4Mg9cWgB8HUvbwg0xYvCPvHtk89apDYq3YTh937FUSeWnQbw4XqgcPvf98XOTTLEqlWkniJf7OzZN89nc2vRAG/CYx8nWVb++Zic2xeqYX9r3Tgmgz+WQ/YGDQZ/wot9iU4+cNV9aWF3K5MlKc+HMdsg9+KaICbRKVyNUcaHkVhmXEP6NQNZl/UFHXy3q+XjxKeEqllRWg3vwW0yr/U3+rvKpyj19Ucwel073exocstVu32PrxoAe6FXyxCSA6E89hiVEgwOqYPHW84a8bn/72aUx8h2AADqAjr+j6neQk6wweWIV+vnYdwVTc2up3HXQAVsc/vJ/xTJnW251r8yod3z2rhyjlUNh/rA3w2jtRmRq8+RYJgSHXSRQfpnlGiQSb0Lljcqkynnbcglhs2sdUi5A3K2xsi9ujHiPd71l2KWhTINOWHs6jkoGf+cCyWpZdD83rgaHa3CtF5gw=
