language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    secure: B8O3rVGCVgBo4dNWSlAVVreI+8OcnQCVh/JYZiiFUv+2M1Xnb4wPBJPklrcR1IG8WTr0pMHVWg+C1arJnOOZYyuGjnWZW+pl2xOhqe3TY2Q7OJ6mDPFFxVI4m2xHW01nIRg/07Be0m7Z+nOh7DZvUqoNYZUyAFeksjqpykMPzUAHZOJHcAjrEKxl+5jjFb3QerIa45OJPv6v1/CHrI2qvtcl4KT9N2H9BL2/XWHQ0PoPiRE3Limsw6P8ongsDcL+cImWPUf1RnMEOX/YU7g/pCEskx8nfeVtHoq75qXJ0GETHk0MLZlf700jCy2dYhlLQagwsAjvwqwQY6H7IANQmmd97bbfucB8xP3x1F95iwCygqQ3HnDvtmrCfWsDhnMsPS19bxBYrNQ4GI8f1nqzFhm5mmM8bCgCViXJrevAYtGrg9tY+hDqdtdJ61hVB5MGkK4WY/FkY0xa7p9dTKTe1b7fHLNdKfFjyKzLuccwcHkJtmT0yUsY6hmsaJD4lo8Cs6CKpsNeKP7+zKJPI4GCaemukLe6iwXJDxu8fS4zryHJ5MPBE6CG/K16g2X4pAciviUeTSGZ+bdVLpnUJSvK5oH/iAFxufIgHV5djOglaCvMXBH3vGjtTAyNAKlKLrqKGs/Lq78pmyfpRguXc/idADeRL6mpyXfvZY0M7xcHgJE=
