language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    secure: RsxSEzkVTf3gG/AHz+Y3Eje+oB53rue3wvea94Kg9oPRZhgotr4mjqQml9ZtEVlvQZ5e7+IZo0JJgb37WuNqqdDicVENaI9h6u6stDbzKdtJOejXz5WRVI5NsQW2GJoKZgdiL+oFxNcj+k6ikZ/NkyNcJdbR44cBuL9TLB/LTKuL77b4VUnBJ5X5Z7hE5XQugGhBc42A8pXAutmKHIYJaxPv9YzWw66mBbM8X/WSHsJdoh7ts7VMas8+bnD6dsArVXRC07k9ykc0MJe7ZIbwKxfb8oz0S/hOodQHacSjlXAiGNANo3vxlNtvPqg0qW1N0KTWBsFQ8m55Lok1ugTgUhCRPGJqrfKuVmd5bE/hkx4IqK+HFdhDVVaw8U+tUZkUqszCPFkGD1IseQdmv9l2JE47oOtDOCiq9OnAR2G2jkHGr+HoPHPf2+8xsznI0ZBaeLat3ZbPOryJH06dIOY04S4bfm9gR6YVA0unsEVGr15P4RfHVOINEiCPwb154TWghqUQpqC62fP82u+wLFf3MHKfGxxnFTWFBmsDdDeNUTYMW41fLYawW6GJacWPBjqdFXDuH56DO4DUptHpDbaJNJYrwZqPbiPSnAoA+TpkfYRWcWouRalDVKwRo/fuS7l8LAuWqWXLBcs+GvcqyLUhyjNWAEll9haAnRb3ivQGe7M=
