language: node_js
cache:
directories:
- node_modules
notifications:
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
dd:
  secure: APVVWBdVNrOUxJma0JiTt0GnxFNTDEsRa+N7MnopAZYCW15VcIK9ScDqBPNvqrnoFUsNDqz+pwwoNrrci3dI7i3hYI7G0mImXWlEUM0iH7UTpCjjduFqI75yYXu3t/dO8pIAas0hXJHtt7o2p8dViQvh86/AFSpgFS0vsyp6YybVpP4JBX3xa6pohO1B9IGsjR/TzXdDCBCRRacJ55/T/cFkcgCi02zP/kn/ydvXsem7+DHumBZRT+fAUNRraCNUn90cUjUjufMiZ123lJ8K6C9GMiAjpmrm+XhK/It/LSAbK5wSaH3smQQcQbcFqwquQp5Q621q7fy2uIt8TSqmxixFSAzQySNkdgkW0XRoXGHN1GP8JxZCLN5/uat0L9njUSqBv5hBBv3egwdgAumfwJrX6JJGll3RBtx9toOF1D6ioca/YZVhAGNdKQTaTmOwE0P90XD7LUTwMIH4eLViRqYLpWVqc8TgVy5AsH4CbkA9CsEJ7xJNfohNh2lYBCIjABQFOvw7BiKMCB7ZDyVOkh0D1nOG9nk7yBGbydveejJSsTVPTlQJzyuU/9YMHl/yBSWbfm+Dv1qCbOxEONaXhFbqoNYMhivV2OB8Vu/AeC1d+HtzHujyBlPOU1A5vF7T/XIoGY21++e0TcBmmgR/+vAVZzdQr7G0v0ZtS/IEPak=
