language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    secure: iqx7w0UDRLSk0TA3cIAfl1OWj8qBcrCLkBj88Ycdg8QpbS7y2Wk/g6kPUGL+3tD6cZjWGAH6sFXLLHtvy/TVVNUP/idwP7U4H6Ep+AL57BEMpORp91emmn0mPzqeLS30uDZ1YjUm0YnTqm1Qwg7pAB0oElXD1Dfcsu/5bQYk1BWn6Z57KKxBEb6PCLnefkEkdOeLj2jtq0pjK/fvQ/3X3efyjOxoB9djoN1++JxRslHGg8pbp7KAYhkBAY90rm/1vXvpMM5voCrJPRnHdr8jftHK4CXFYKuNfnc3EkhZpVKjQUyjnvbm8RPu/QCEA44b6MSM3gXfDa4uMi1HJYIJBBR5za6jOGXV58EepR94hgS81GagSg6XlJOXOHNLNYkYzNoDMPrBARng4gDWJfnx+fAZERUWcQanVW8pjlng5UVfIPMb6y/g8vIUsQX4Ahj6+A8O+zqxQEZoeSYoEGPm78FVKUIEMEoHMQfY2kzY6Cv2XYPflHvkhcbBdUuOsqZPFhcpmgWLcVdrNQWpIrTbw7c1jP06STebRHI+8NVQ+GLhxeSgx3nK/beNg8gNGJlP4lGdp5FHxJn6i9SADSxAirUcgQ+QqRHqWpE73ztsBQxXY8E6/r2q6KSipvHVnvygdTIq74qnpR+6fmrb9jxUayhaakHOr6MSsMZhOX9R2Y8=
