language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    secure: lFoDWa5vG/QSTJ1pYPNO1RYJYtxgyfjltoazcXCeUljriRbUx/CPZzg5CSQ50mMhEGFcJA0cLNtYSNkYpII4dLqGN1F5YNH+S0pTjD99CbtuwErATbnRVa5dvok1GyuA1/cSVnUyorabNH2HfzfwzhuPUVPYejL+bRloBlz+dAiExWcLwSJo9KmogRdB0lBwpS6yWBqbILyr6Mm6310oWJ6rT6EAzVFExE9SYNbIbsVjipow5DJGM6/uW5A5amOhdiLmk62Bwk0PylEz5DPpVh/sZN8khKBdh1Bhi2gKW33GhXciVbYqka6nYijoZicgjKxMBNcaMrIffsccSUBpDz3FUq6rmAvzO7CuIBSryoUJA7uJ15PU2VQuINd0S+R/tYSUTIE1NooQ+9B+YhwbxyWnRKCoDLkEogRwm7rxbSnDXdtePpBdg7Qypqu3bNBOkUPd4W4lHptsXssgmTUdHKm6rSn3aB/0bwRGFxpD68O5YKDxJ4Ph8crbdR9fshrvE9falWy7Xl1dkb9GVEOrOn+ZIF4d8GKLAxb4IfJaY+KCQ2I2Bq8YSeo9Ni5P+7lagjx72t6b94jFxcVOb97m1Csf7h8wMXaYSFzktcJmuGcUcvdUtl/pOiibeCAv9um+MPHBwIMwT4dCEYv2yUN3eJ+0AS32C8QNo7NKKCkh3Rw=
