language: node_js
cache: 
directories:
- node_modules
notifications: 
email: false
node_js:
- '7'
script: node index.js
except:
- "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    secure: FQX/tCSlOX2hG98sTBfV2PJa92dFxkOwiVadKtmrlM+I3qSKQdArYXX2KczncYYX0/jlEizJ/Wgxm1Vt1V3ILlk9JNBabrCW0ziMeaKa6IbJ9pN3mkjBXINpKkEY0ouEl/iPfZ+aDAEug+xXmmNCxU9beJWkpzakx/xqIDrSe7+qR5+evTAfuazBt4nVNz4/glY26Rng5TUkazTwf6CWSH5IQGazXuaViN4Nn/oLTXhznjIMBLXtejHjK898Zs73o+Ys6QmToNyKX134AeB8cs6tWhyFqVLkcvyidGKPdjPegWGjEKnIIXYpl8QoIUbB5e9R+nykbVkuxZTYgveY3f3vIQ6IhRQpadAdLbgGAyhD3aOaXqxwOAFh92ta/kq8fnYl97tOGrL69j6/V6zXTcOsek4yweywwT6G9TmXoEj7iH/X1ihQ7I7973X2pjeNyNOhUWmkK+UHDcrGxsb5EbnZJrdKcV8av8Jm0c+cRF3sD599u44m0IaHGEuVtpfTaXdvyUVuf5Ob866c9ToO3KDomMpumP6OI/8J/gQvVFFgDYHI69fvTLDYMclCE5QXjIfkxhjxT4lzwrjntW46f7wkQdcLKMKwCrncH6TJnwgzVMLo4anBWxV0RkBTNU6AtrY5zZOQ5z2lTkHpOjr2zPpwl4dQxGz8J/BzT7Jbcgw=
